apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: wso2mi-hl7-demo-docker
  name: wso2mi-hl7-demo-docker
spec:
  ports:
  - name: "8280"
    port: 8280
    targetPort: 8280
  - name: "9292"
    port: 9292
    targetPort: 9292
  - name: "8290"
    port: 8290
    targetPort: 8290
  - name: "20000"
    port: 20000
    targetPort: 20000
  - name: "9393"
    port: 9393
    targetPort: 9393
  - name: "9494"
    port: 9494
    targetPort: 9494
  - name: "9595"
    port: 9595
    targetPort: 9595
  selector:
    io.kompose.service: wso2mi-hl7-demo-docker
status:
  loadBalancer: {}
